#Travis CI 설정은 YAML(야믈)을 통해서 함
language: java
jdk:
  -openjdk8

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전 수행(jar+기타 설정파일을 모아 압축(zip))
before_deploy:
  - zip -r freelec-springboot2-webservice
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

# 외부 서비스와 연동될 행위 선언 (S3로 파일 업로드 or CodeDeploy로 배포 등)
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot-build-bucket # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리 (이 위치의 파일들만 S3로 전송)
    wait-until-deployed: true
    before_install:
      - chmod +x gradlew

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - shinyul2720@gmail.com
