# CodeDeploy 명령 담당
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

# CodeDeploy에서 EC2로 넘겨준 파일들 모두 ec2-user권한을 갖도록 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user